[package]
name = "eth-fabulous"
version = "0.1.0"
authors = ["TovarishFin <tovarishfin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
secp256k1 = "0.16.0"
rand = "0.7.2"
sha3 = "0.8.2"
regex = "1.3.1"
num_cpus = "1.11.1"
colored = "1.9.0"
rayon = "1.3.0"
